# Unique identifier of the project to analyze
sonar.projectKey=gayathri-ms2006_ecommerce-v2

# Organization key in SonarCloud
sonar.organization=gayathri-ms2006

# Path to the source directories (relative to this file)
sonar.sources=.

# Exclusions for directories and files that shouldn't be analyzed
sonar.exclusions=**/node_modules/**, **/.terraform/**, **/coverage/**, **/dist/**, **/build/**, **/*.tfstate

# Source code encoding
sonar.sourceEncoding=UTF-8
