@echo off
echo Importing CloudFront Origin Access Control...
terraform import aws_cloudfront_origin_access_control.ecommerce E2GX88HWY1KJ3Q

echo Importing CloudFront Distribution...
terraform import aws_cloudfront_distribution.ecommerce E32J4PC8PSE27H

echo Importing S3 Bucket...
terraform import aws_s3_bucket.frontend gayathrifrontend

echo Importing S3 Encryption...
terraform import aws_s3_bucket_server_side_encryption_configuration.frontend gayathrifrontend

echo Importing S3 Public Access Block...
terraform import aws_s3_bucket_public_access_block.frontend gayathrifrontend

echo Importing S3 Ownership Controls...
terraform import aws_s3_bucket_ownership_controls.frontend gayathrifrontend

echo Importing S3 Bucket Policy...
terraform import aws_s3_bucket_policy.frontend gayathrifrontend

echo Importing SNS Topic...
terraform import aws_sns_topic.order_events arn:aws:sns:ap-southeast-1:726101441380:order-events-topic-g

echo Importing SNS Subscriptions...
terraform import aws_sns_topic_subscription.inventory arn:aws:sns:ap-southeast-1:726101441380:order-events-topic-g:05411d77-79c0-4922-b8bc-c43f397e2b05
terraform import aws_sns_topic_subscription.payment arn:aws:sns:ap-southeast-1:726101441380:order-events-topic-g:8c98d049-67f6-4b9d-a642-1df2d127ba54
