name: Frontend Tests

on:
  push:
    branches:
      - main
    paths:
      - 'ecommerce-frontend/**'
      - '.github/workflows/frontend-test.yml'

  pull_request:
    branches:
      - main
    paths:
      - 'ecommerce-frontend/**'
      - '.github/workflows/frontend-test.yml'

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ecommerce-frontend

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm install

      - name: Run Frontend Tests
        run: npm test -- --watchAll=false