name: Order Service Tests

on:
  push:
    branches:
      - main
    paths:
      - 'ecommerce-microservices/order-service/**'
  pull_request:
    branches:
      - main
    paths:
      - 'ecommerce-microservices/order-service/**'

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ecommerce-microservices/order-service

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: ecommerce-microservices/order-service/package-lock.json

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test
